"""Add coloumn

Revision ID: 03d01d9df9a5
Revises: 964470b75239
Create Date: 2025-06-15 01:00:35.418875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d01d9df9a5'
down_revision = '964470b75239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_cost', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('min_stock', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reorder_point', sa.Integer(), nullable=True))

    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('document_ref', sa.String(length=100), nullable=True))
        batch_op.drop_index('ix_movements_shop_product')
        batch_op.create_index('ix_movements_shop_inventory', ['shop_id', 'inventory_id'], unique=False)
        batch_op.drop_constraint('inventory_movements_product_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'inventory', ['inventory_id'], ['id'])
        batch_op.drop_column('product_id')
        batch_op.drop_column('cost_per_unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_per_unit', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('inventory_movements_product_id_fkey', 'products', ['product_id'], ['id'])
        batch_op.drop_index('ix_movements_shop_inventory')
        batch_op.create_index('ix_movements_shop_product', ['shop_id', 'product_id'], unique=False)
        batch_op.drop_column('document_ref')
        batch_op.drop_column('inventory_id')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('reorder_point')
        batch_op.drop_column('min_stock')
        batch_op.drop_column('supplier_cost')

    # ### end Alembic commands ###
