"""Rinominato type in addon_type

Revision ID: 347ef8a3978a
Revises: 5c3d9cbed256
Create Date: 2025-03-04 02:32:24.540860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '347ef8a3978a'
down_revision = '5c3d9cbed256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cms_addons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('addon_type', sa.String(length=255), nullable=False))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cms_addons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('addon_type')

    # ### end Alembic commands ###
