"""Aggiunte colonne per rinnovo dominio, rimosse vecchie colonne DNS

Revision ID: 3ef9f2f4ab7b
Revises: adcfb25f21f5
Create Date: 2025-04-18 22:29:17.084946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef9f2f4ab7b'
down_revision = 'adcfb25f21f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.add_column(sa.Column('renewal_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('renewal_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('record_cname')
        batch_op.drop_column('record_ns')
        batch_op.drop_column('record_aaaa')
        batch_op.drop_column('record_a')
        batch_op.drop_column('record_srv')
        batch_op.drop_column('record_mx')
        batch_op.drop_column('record_txt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.add_column(sa.Column('record_txt', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('record_mx', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('record_srv', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('record_a', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('record_aaaa', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('record_ns', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('record_cname', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('renewal_date')
        batch_op.drop_column('renewal_enabled')

    # ### end Alembic commands ###
