"""Added product_images and product_attributes tables with EAN support

Revision ID: 5c3d9cbed256
Revises: 10a5ad139cfc
Create Date: 2025-03-04 01:43:59.683101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c3d9cbed256'
down_revision = '10a5ad139cfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_attributes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('attribute_name', sa.String(length=100), nullable=False),
    sa.Column('attribute_value', sa.String(length=100), nullable=False),
    sa.Column('price_modifier', sa.Float(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('variant_image_url', sa.String(length=512), nullable=True),
    sa.Column('ean_code', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ean_code')
    )
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ean_code', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['ean_code'])
        batch_op.drop_constraint('products_category_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('products_brand_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'brands', ['brand_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('products_brand_id_fkey', 'brands', ['brand_id'], ['id'])
        batch_op.create_foreign_key('products_category_id_fkey', 'categories', ['category_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('ean_code')

    op.drop_table('product_images')
    op.drop_table('product_attributes')
    # ### end Alembic commands ###
