"""Aggiunta logica plugin/grapesjs/app

Revision ID: 74fd6dfd07b3
Revises: 9f4a6b0ff850
Create Date: 2025-04-08 21:55:36.226371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74fd6dfd07b3'
down_revision = '9f4a6b0ff850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cms_addons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_theme_json', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_block_json', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_integration', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('integration_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('preview_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cms_addons', schema=None) as batch_op:
        batch_op.drop_column('preview_image')
        batch_op.drop_column('integration_key')
        batch_op.drop_column('is_integration')
        batch_op.drop_column('is_block_json')
        batch_op.drop_column('is_theme_json')

    # ### end Alembic commands ###
