"""Fix Page FK and unique slug per shop/lang

Revision ID: 9e6adbb02b6d
Revises: 74fd6dfd07b3
Create Date: 2025-04-08 23:10:14.520645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e6adbb02b6d'
down_revision = '74fd6dfd07b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.drop_constraint('pages_slug_key', type_='unique')
        batch_op.create_unique_constraint('uq_slug_shop_lang', ['slug', 'shop_name', 'language'])
        batch_op.create_foreign_key(None, 'ShopList', ['shop_name'], ['shop_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_slug_shop_lang', type_='unique')
        batch_op.create_unique_constraint('pages_slug_key', ['slug'])
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###
