"""Aggiunta colonna styles alla tabella pages

Revision ID: 9f4a6b0ff850
Revises: 347ef8a3978a
Create Date: 2025-03-15 22:24:02.861001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f4a6b0ff850'
down_revision = '347ef8a3978a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('styles', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_column('styles')

    # ### end Alembic commands ###
